project:
  type: website

website:
  title: "Aishwarya Deengar"
  navbar:
    background: primary
    logo: "docs/img/i.jpg"
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Resume
        href: cv/index.qmd

    right:
      - icon: github
        text: Github
        href: https://github.com/AishwaryaD1
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/aishwaryadeengar/
      - icon: envelope
        text: Email
        href: "mailto:mail.axd1174@case.edu"   

format:
  html:
    theme: united
    dark: darkly
    css: html/styles.css
    toc: true

editor: visual

search: true

execute:
  freeze: true