project:
  type: website

website:
  title: "Aishwarya Deengar"
  navbar:
    background: primary
    logo: "docs/img/i.jpg"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Resume.qmd
        text: Resume

format:
  html:
    theme: united
    dark: darkly
    css: styles.css
    toc: true

editor: visual

